### ISSUE TITLE
Dogs cannot be heard first time entering 212

### ISSUE THREAD

**Issue by IntelOrca** [IntelOrca/openre#15]
1. Start Leon A
2. Jump to room 212 Back Alley
3. Dogs are silent

Seems to be fine loading a saved game where they have already jumped down.

**Comment by elmarsan** [comment]
We have the same issue in room 204 with the licker.
It does not matter if you go to another room and come back (same with jumping); the licker remains silent.
However, as you mentioned, if you load the game and then return to room 204, the licker's sounds work again.
